# Nmpy

In [1]:
import numpy as np

In [2]:
# creating an array

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b = np.array([1,2.3,"abc",True])

In [6]:
b

array(['1', '2.3', 'abc', 'True'], dtype='<U32')

# Properties of array

In [7]:
a1 = np.array([10,20,30,40])

In [8]:
a1

array([10, 20, 30, 40])

In [10]:
a1.ndim

1

In [11]:
a1.dtype

dtype('int32')

In [12]:
a1.shape

(4,)

In [13]:
a1.size

4

In [14]:
a1.itemsize

4

# Different ways of creating array

In [15]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [16]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
np.array(np.random.randn(5),dtype="int")

array([ 0,  0,  0,  0, -1])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.array([1,2,3],dtype="float")

array([1., 2., 3.])

# Multidimentional array

In [32]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [33]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
np.array([[1,2,3],[4,5,6]]).reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [39]:
a = np.random.randn(24).reshape(2,3,4)

In [40]:
a

array([[[ 1.20536241, -0.03665622,  0.45110705,  1.52351368],
        [ 0.05898073,  1.72811345,  0.70995532, -1.34897709],
        [-0.39499164,  0.80597587,  0.15621713,  1.38769862]],

       [[-1.17062276,  0.06705831, -2.1618211 , -0.66421586],
        [ 0.2864377 ,  1.76449478, -0.43080699, -0.62547776],
        [-0.49356915,  0.59581507, -1.73630925,  1.23329333]]])

In [41]:
a.dtype

dtype('float64')

In [42]:
a.itemsize

8

In [43]:
a.size

24

In [44]:
a.shape

(2, 3, 4)

In [45]:
a.ndim

3

# Array Functions

In [46]:
a = np.arange(10,20).reshape(2,5)

In [47]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
a.sum()

145

In [52]:
a.sum(axis=0) #column wise addition (vertical addition)

array([25, 27, 29, 31, 33])

In [53]:
a.sum(axis = 1) #row wise addition (horizontal addition)

array([60, 85])

In [54]:
a.max()

19

In [57]:
a.min()

10

In [58]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
a.max(axis=0)

array([15, 16, 17, 18, 19])

In [61]:
a.max(axis=1)

array([14, 19])

In [62]:
a.min(axis=0)

array([10, 11, 12, 13, 14])

In [63]:
a.min(axis=1)

array([10, 15])

In [64]:
a.mean()

14.5

In [65]:
a.var()

8.25

In [66]:
a.std()

2.8722813232690143

# Numpy Functions

In [82]:
a = np.array([1,1,2,2,2,2,2,3,3,3,4,4,5,6,7,8,9])

In [83]:
a

array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 6, 7, 8, 9])

In [84]:
np.mean(a)

3.764705882352941

In [85]:
np.median(a)

3.0

In [86]:
q1 = np.quantile(a,0.25)

In [87]:
q3 = np.quantile(a,0.75)

In [88]:
iqr = q3 - q1

In [89]:
iqr

3.0

In [90]:
upper_range = q3 + 1.5*iqr

In [91]:
lower_range = q1 - 1.5*iqr

In [92]:
upper_range

9.5

In [93]:
lower_range

-2.5

# Math Functions

In [94]:
np.sin(90)

0.8939966636005579

In [95]:
np.cos(90)

-0.4480736161291701

In [96]:
np.log(10)

2.302585092994046

In [97]:
np.log(1)

0.0

In [99]:
np.log10(10)

1.0

In [100]:
np.log(np.log10(5))

-0.35814744992084513

In [101]:
np.sqrt(144)

12.0

# Reducing skewnewss

In [102]:
a = np.array([1,2,2,3,3,3,4,4,16,20,25])

In [103]:
a

array([ 1,  2,  2,  3,  3,  3,  4,  4, 16, 20, 25])

In [104]:
np.mean(a)

7.545454545454546

In [105]:
np.median(a)

3.0

In [106]:
from scipy.stats import skew

In [107]:
skew(a)

1.1712731595847037

In [108]:
a = np.sqrt(a)

In [109]:
a

array([1.        , 1.41421356, 1.41421356, 1.73205081, 1.73205081,
       1.73205081, 2.        , 2.        , 4.        , 4.47213595,
       5.        ])

In [110]:
skew(a)

0.9630668329521322

In [111]:
a1 = np.arange(10,16).reshape(3,2)

In [112]:
a2 = np.arange(16,22).reshape(3,2)

In [113]:
a1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [114]:
a2

array([[16, 17],
       [18, 19],
       [20, 21]])

In [119]:
np.concatenate([a1,a2])

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [120]:
np.concatenate([a1,a2],axis=1)

array([[10, 11, 16, 17],
       [12, 13, 18, 19],
       [14, 15, 20, 21]])

In [121]:
np.unique([1,2,2,3])

array([1, 2, 3])

In [122]:
np.unique([1,1,2,3],return_counts = True)

(array([1, 2, 3]), array([2, 1, 1], dtype=int64))

# Indexing and Slicing

In [123]:
a = np.arange(10,20).reshape(5,2)

In [124]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [173]:
a[1] #indexing start from zero  #important

2

In [126]:
a[1,1]

13

In [128]:
a[1][1]

13

In [129]:
a[4,0]

18

In [130]:
a[4][0]

18

In [131]:
a[2:4,]

array([[14, 15],
       [16, 17]])

In [134]:
a[2:4,0:2]

array([[14, 15],
       [16, 17]])

In [136]:
a[2:4,1]

array([15, 17])

In [137]:
a[2,0]

14

In [ ]:
a[3,1]

In [140]:
a[[0,2]]

array([[10, 11],
       [14, 15]])

In [141]:
a[[0,2],1]

array([11, 15])

In [142]:
a[[0,2],0]

array([10, 14])

# Boolean Indexing

In [143]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [144]:
a > 15

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [145]:
a[a > 15]

array([16, 17, 18, 19])

In [146]:
a[a % 2 == 0]

array([10, 12, 14, 16, 18])

In [147]:
a[a % 2 != 0]

array([11, 13, 15, 17, 19])

# Vectorization

In [148]:
a = np.array([1,2,3])

In [149]:
a

array([1, 2, 3])

In [150]:
s = 10

In [151]:
a + s

array([11, 12, 13])

In [154]:
np.array([2,3,4])*10

array([20, 30, 40])

# Broadcasting

In [155]:
a1 = np.array([[1,2],[3,4]])

In [156]:
a1

array([[1, 2],
       [3, 4]])

In [157]:
a2 = np.array([2,3])

In [158]:
a2

array([2, 3])

In [159]:
a1 + a2

array([[3, 5],
       [5, 7]])

# Cross Product vs Dot Product

In [161]:
a1 = np.array([2,4])

In [162]:
a2 = np.array([-4,2])

In [163]:
a1

array([2, 4])

In [164]:
a2

array([-4,  2])

In [166]:
#cross product
np.cross(a1,a2)

array(20)

In [168]:
#dot product
np.dot(a1,a2)

0

In [169]:
m1 = [[1,2],[2,4]]

In [170]:
m2 = [[5,6],[7,8]]

In [171]:
np.cross(m1,m2)

array([ -4, -12])

In [172]:
np.dot(m1,m2)

array([[19, 22],
       [38, 44]])